version: "3.8"

services:
  splash:
    image: scrapinghub/splash:3.5
    networks:
      - brige-network

  spider:
    build: ./
    networks:
      - brige-network
    depends_on:
      - splash
    volumes:
      - ./:/source
    working_dir: /source
    command: python entrypoint.py

networks:
  brige-network:
